### ISSUE TITLE
redis plugin only monitors one port

### ISSUE THREAD

**Issue by 72squared** [MeetMe/newrelic-plugin-agent#195]
I pre-sharded my redis data and am currently running multiple instances of redis on a single server in anticipation of spreading the data across many machines in the future. However I cannot figure out how to monitor multiple redis instances on the same server with this plugin. It seems to show data from only one of the shards.

**Comment by cfornfeist** [comment]
I actually get:

------------------------------------------------------------------------ [START]
/usr/local/bin/newrelic-plugin-agent Exception [2015-03-02T17:32:52.146031]
------------------------------------------------------------------------- [INFO]
Interpreter: /usr/bin/python
CLI arguments: /usr/local/bin/newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg
Exception: too many values to unpack
Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/helper/unix.py", line 92, in start
    self.controller.start()
  File "/usr/local/lib/python2.7/dist-packages/helper/controller.py", line 266, in start
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/helper/controller.py", line 253, in run
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 118, in process
    self.start_plugin_polling()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 280, in start_plugin_polling
    self.config.application.get(plugin))
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 108, in poll_plugin
    thread.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 308, in thread_process
    obj.poll()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/plugins/base.py", line 287, in poll
    data = self.fetch_data(connection)
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/plugins/redis.py", line 148, in fetch_data
    key, value = line.strip().split(':')
ValueError: too many values to unpack
-------------------------------------------------------------------------- [END]

with that configuration.
