### ISSUE TITLE
Problem starting the plugin agent

### ISSUE THREAD

**Issue by kcarwile** [MeetMe/newrelic-plugin-agent#261]
Not sure where to go from here. I get the following error when trying to start the plugin agent. I am logged in as root.

Traceback (most recent call last):
  File "/usr/bin/newrelic_plugin_agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.0.0

When I do a "pip list", this is the output
argparse (1.1)
distribute (0.6.10)
ethtool (0.6)
helper (2.4.1)
importlib (1.0.3)
iniparse (0.3.1)
iotop (0.3.2)
iwlib (1.0)
logutils (0.3.3)
newrelic-plugin-agent (1.2.3)
nose (0.10.4)
numpy (1.4.1)
pip (1.5.4)
pycurl (7.19.0)
pygpgme (0.1)
python-dateutil (1.4.1)
pytz (2010h)
PyYAML (3.10)
requests (2.2.1)
setuptools (0.6c11)
urlgrabber (3.9.1)
yum-metadata-parser (1.1.2)

As you can see, my requests version meets the criteria >= 2.0.0

**Comment by AJ2090** [comment]
i am getting following error even after removing line requests>= as suggested...
Traceback (most recent call last):
  File "/usr/bin/newrelic-plugin-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: argparse

and my pip list output is as follows:
argparse (1.4.0)
distribute (0.6.10)
gyp (0.1)
helper (2.4.1)
importlib (1.0.3)
iniparse (0.3.1)
logutils (0.3.3)
meld3 (1.0.2)
MySQL-python (1.2.3rc1)
newrelic-plugin-agent (1.3.0)
ordereddict (1.2)
pip (7.1.0)
policycoreutils-default-encoding (0.1)
pycurl (7.19.0)
pygpgme (0.1)
pymongo (3.1.1)
PyYAML (3.11)
requests (2.8.1)
setools (1.0)
setuptools (0.6rc11)
supervisor (3.1.3)
urlgrabber (3.9.1)
yum-metadata-parser (1.1.2)

**Comment by AJ2090** [comment]
problem solved by updating setuptools. Now its working ..
