### ISSUE TITLE
Cant start agent

### ISSUE THREAD

**Issue by peter-fritchley** [MeetMe/newrelic-plugin-agent#272]
When I try to start the agent I get the following error:

``` bash
Starting /usr/bin/newrelic_plugin_agent: Traceback (most recent call last): 
File "/usr/bin/newrelic_plugin_agent", line 5, in <module> 
from pkg_resources import load_entry_point 
File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module> 
working_set.require(__requires__) 
File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require 
needed = self.resolve(parse_requirements(requirements)) 
File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve 
raise DistributionNotFound(req) 
pkg_resources.DistributionNotFound: requests>=2.0.0
```

we have requests 2.2.1 running on the server:

``` bash
[root@CPL-HADB-01]# pip list | grep "requests" 
requests (2.2.1)
```

Thanks.

**Comment by rakslice** [comment]
I ran into the same error message; a quick `pip install requests --upgrade` got past it.

**Comment by dsavinkov** [comment]
@rakslice 
I worked just fine! Thanks
