### ISSUE TITLE
pkg_resources.DistributionNotFound: requests>=2.0.0

### ISSUE THREAD

**Issue by OliverKellyATech** [MeetMe/newrelic-plugin-agent#356]
Hi,

When trying to start the newrelic_plugin_agent daemon I get the following Python traceback error:

```
# service newrelic-plugin-agent restart
 * Stopping New Relic Plugin Agent newrelic-plugin-agent                                                                                                                            No process in pidfile '/var/run/newrelic/newrelic-plugin-agent.pid' found running; none killed.
                                                                                                                                                                             [ OK ]
 * Starting New Relic Plugin Agent newrelic-plugin-agent                                                                                                                            Traceback (most recent call last):
  File "/usr/local/bin/newrelic-plugin-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.0.0
```

The server is Ubuntu 12.04.5, running newrelic-plugin-agent 1.3.0 and requests 2.4.3:

```
# pip list | egrep "(newrelic|requests)"
newrelic-plugin-agent (1.3.0)
requests (2.4.3)
```

When updating newrelic-plugin-agent (just to be sure), it tries to install an updated version on requests even though the requirement is met. While updating requests simply says it is up to date:

```
# pip install newrelic-plugin-agent --upgrade
Requirement already up-to-date: newrelic-plugin-agent in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: helper>=2.2.2 in /usr/local/lib/python2.7/dist-packages (from newrelic-plugin-agent)
Downloading/unpacking requests>=2.0.0 from https://pypi.python.org/packages/2.7/r/requests/requests-2.4.3-py2.py3-none-any.whl#md5=0a66a9c4c22272680430fbb9fb4ca34f (from newrelic-plugin-agent)
  Downloading requests-2.4.3-py2.py3-none-any.whl (459kB): 459kB downloaded
Requirement already up-to-date: pyyaml in /usr/local/lib/python2.7/dist-packages (from helper>=2.2.2->newrelic-plugin-agent)
Installing collected packages: requests
  Found existing installation: requests 2.4.1
    Uninstalling requests:
      Successfully uninstalled requests
Successfully installed requests
Cleaning up...
```

and:

```
# pip install requests --upgrade
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```

I've tried removing requests form the requirements in `/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent-1.3.0.egg-info/requires.txt`, and while this allows the daemon to start without the traceback, I don't believe it is working correctly. For example: the agent reports "No metrics to send" even though the HAProxy stanza is enabled in `newrelic-plugin-agent.cfg` and stats are available.

Any help would be greatly appreciated!

**Comment by chrisvoo** [comment]
It seems to affect also RHEL 6:
```
[ ~]$ sudo pip install newrelic-plugin-agent
Collecting newrelic-plugin-agent
  Using cached newrelic_plugin_agent-1.3.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): helper>=2.2.2 in /usr/lib/python2.6/site-packages (from newrelic-plugin-agent)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.0.0 in /usr/lib/python2.6/site-packages (from newrelic-plugin-agent)
Requirement already satisfied (use --upgrade to upgrade): importlib in /usr/lib/python2.6/site-packages (from newrelic-plugin-agent)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib64/python2.6/site-packages (from helper>=2.2.2->newrelic-plugin-agent)
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.6/site-packages (from helper>=2.2.2->newrelic-plugin-agent)
Requirement already satisfied (use --upgrade to upgrade): logutils in /usr/lib/python2.6/site-packages (from helper>=2.2.2->newrelic-plugin-agent)
Installing collected packages: newrelic-plugin-agent
  Running setup.py install for newrelic-plugin-agent
Successfully installed newrelic-plugin-agent-1.3.0
[cl027620@datawarehouse ~]$ sudo newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg 
Traceback (most recent call last):
  File "/usr/bin/newrelic-plugin-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2659, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.0.0
```

**Comment by phpcodemonkey** [comment]
@chrisvoo I fixed this on CentOS 6 (RHEL 6) with:

```
pip install --upgrade setuptools
```
which upgrades the distro provided setuptools-0.6rc11 to later setuptools-18.0.1
