### ISSUE TITLE
TypeError: name must be an instance of basestring(MongoDB)

### ISSUE THREAD

**Issue by rahsaanpage** [MeetMe/newrelic-plugin-agent#357]
Hello Team,

i seem to have this weird issue where pymongo returns this "TypeError: name must be an instance of basestring(MongoDB) error".  

 newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg -f
INFO       2014-10-27 18:33:33,177 14628  MainProcess     MainThread newrelic_plugin_agent.agent                   **init**                  L55    : Agent v1.3.0 initialized, Linux-2.6.18-274.0.0.0.1.el5-x86_64-with-glibc2.2.5 (Red Hat Enterprise Linux Server 5.7 Tikanga) CPython v2.7.0
INFO       2014-10-27 18:33:33,177 14628  MainProcess     MainThread helper.controller                             run                       L251   : newrelic-plugin-agent v2.4.1 started
INFO       2014-10-27 18:33:33,177 14628  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: mongodb
Traceback (most recent call last):
  File "/opt/python27/bin/newrelic-plugin-agent", line 9, in <module>
    load_entry_point('newrelic-plugin-agent==1.3.0', 'console_scripts', 'newrelic-plugin-agent')()
  File "/opt/python27/lib/python2.7/site-packages/newrelic_plugin_agent/agent.py", line 337, in main
    helper.start(NewRelicPluginAgent)
  File "/opt/python27/lib/python2.7/site-packages/helper/**init**.py", line 174, in start
    obj.start()
  File "/opt/python27/lib/python2.7/site-packages/helper/controller.py", line 266, in start
    self.run()
  File "/opt/python27/lib/python2.7/site-packages/helper/controller.py", line 253, in run
    self.process()
  File "/opt/python27/lib/python2.7/site-packages/newrelic_plugin_agent/agent.py", line 118, in process
    self.start_plugin_polling()
  File "/opt/python27/lib/python2.7/site-packages/newrelic_plugin_agent/agent.py", line 280, in start_plugin_polling
    self.config.application.get(plugin))
  File "/opt/python27/lib/python2.7/site-packages/newrelic_plugin_agent/agent.py", line 108, in poll_plugin
    thread.run()
  File "/opt/python27/lib/python2.7/threading.py", line 483, in run
    self.**target(_self.__args, *_self.__kwargs)
  File "/opt/python27/lib/python2.7/site-packages/newrelic_plugin_agent/agent.py", line 308, in thread_process
    obj.poll()
  File "/opt/python27/lib/python2.7/site-packages/newrelic_plugin_agent/plugins/mongodb.py", line 256, in poll
    self.get_and_add_server_stats()
  File "/opt/python27/lib/python2.7/site-packages/newrelic_plugin_agent/plugins/mongodb.py", line 250, in get_and_add_server_stats
    self.config.get('admin_password'))
  File "/opt/python27/lib/python2.7/site-packages/pymongo/database.py", line 884, in authenticate
    "of %s" % (basestring.__name**,))
TypeError: name must be an instance of basestring

**Comment by pocketwalker** [comment]
any update? which version of pymongo will not go into this issue? my version is 2.7.1, is that a problem?
