### ISSUE TITLE
'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by tak-aryelle** [MeetMe/newrelic-plugin-agent#378]
After upgrading some debian packages the plugin agent won't start anymore. Output is:

```
# service newrelic-plugin-agent start
[....] Starting New Relic Plugin Agent: newrelic-plugin-agentTraceback (most recent call last):
File "/usr/local/bin/newrelic-plugin-agent", line 9, in <module>
load_entry_point('newrelic-plugin-agent==1.3.0', 'console_scripts', 'newrelic-plugin-agent')()
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
return ep.load()
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
['__name__'])
File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 10, in <module>
import requests
File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
from .packages.urllib3.contrib import pyopenssl
File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
failed! 
```

Anybody a suggestion?

**Comment by tak-aryelle** [comment]
I could solve the problem by downgrading python-minimal from 2.7.8-2 to 2.7.3-4+deb7u1
