### ISSUE TITLE
Agent not starting pkg_resources.py issue

### ISSUE THREAD

**Issue by turagittech** [MeetMe/newrelic-plugin-agent#387]
Hi 
I have just installed the newrelic plugin agent on Redhat 6.5 using Python 2.6 getting the following
`Starting /usr/bin/newrelic-plugin-agent: Traceback (most recent call last):
  File "/usr/bin/newrelic-plugin-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: argparse`

I have tried the various ideas such as making sure packages are up to date, tried the removing line from requires.txt /usr/lib/python2.6/site-packages/newrelic_plugin_agent-1.3.0-py2.6.egg-info/requires.txt and nothing is resolving it

Thanks for any assistance

**Comment by kijensky** [comment]
I had the same error on Centos (AWS EC2).

You have to install ```yum install python-setuptools``` or update requests ```pip install requests --upgrade```

**Comment by nukedart** [comment]
I have the same error as well on CentOs on Ec2. 

I updated pip and python-setuptools are installed and up to date. I get the same exact error message and am wondering what I may be missing?

**Comment by moacybarros** [comment]
I have the same error, pip and python-setuptools are installed and up to date. Any news about it?

**Comment by marcusl33beach** [comment]
I am running into the same issue. Did you all solve this?

**Comment by ircstones** [comment]
I am having the exact same error, and it is on 1 of 3 in an ELB cluster where every RHEL image is the same.   Did anyone solve this, as I'm stuck.

**Comment by AJ2090** [comment]
For me same issue after removing request>= line from requirements.txt. Does anybody have a solution...

**Comment by AJ2090** [comment]
I got it started by upgrading setuptools. execute command pip install -U setuptools and try again.
No need to remove line requests>= in requirements.txt
