### ISSUE TITLE
DistributionNotFound

### ISSUE THREAD

**Issue by emcconne** [MeetMe/newrelic-plugin-agent#393]
I am on RHEL6.4 and am trying to get newrelic_plugin_agent 1.3.0 to start.  I am using python 2.6.6 and have the following list of python packages 

argparse (1.3.0)
decorator (3.0.1)
distribute (0.6.10)
ethtool (0.6)
helper (2.4.1)
importlib (1.0.3)
iniparse (0.3.1)
iwlib (1.0)
logutils (0.3.3)
M2Crypto (0.20.2)
newrelic-plugin-agent (1.3.0)
pip (6.0.8)
pycurl (7.19.0)
pygpgme (0.1)
pyOpenSSL (0.10)
python-dateutil (1.4.1)
python-dmidecode (3.10.13)
PyXML (0.8.4)
PyYAML (3.11)
requests (2.5.3)
rhnlib (2.5.22)
rhsm (1.8.17)
setuptools (0.6rc11)
simplejson (2.0.9)
slip (0.2.20)
slip.dbus (0.2.20)
slip.gtk (0.2.20)
urlgrabber (3.9.1)
yum-metadata-parser (1.1.2)

When executing newrelic-plugin-agent I get:
Traceback (most recent call last):
  File "/usr/bin/newrelic-plugin-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.0.0

I have to comment out helper>=2.2.2 and requests>=2.0.0 in /usr/lib/python2.6/site-packages/newrelic_plugin_agent-1.3.0-py2.6.egg-info/requires.txt before the agent can start.  Any ideas why DistributionNotFound for requests and then argparse happen when starting?  Are there any problems with the approach I've outlined?

**Comment by rscalize** [comment]
Have you find any solution? Here I have the same issue.

**Comment by ricotijsen** [comment]
_pip install distribute --upgrade_ solved this for me

**Comment by StephenWeber** [comment]
_pip install distribute --upgrade_ solved this for me as well.

**Comment by ralphct** [comment]
Another sort-of solution I found seems to work for a while is:

yum reinstall python-argparse python-requests

...although the distribute --upgrade solution works more permanently.

It seems like something on the system does a "pip install argparse" or "pip install requests" that upgrades one or both of those libraries. From then on, the plugin agent refuses to start - I can't figure out why. There seem to be reasonably reliable solutions though :-)
