### ISSUE TITLE
Unable to run newrelic plugin agent on background

### ISSUE THREAD

**Issue by mosesgumi** [MeetMe/newrelic-plugin-agent#397]
Hi, I can only run the plugin on the foreground but not on the background. Please help

root@ip-10-11-13-114:/etc/newrelic# newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg

ERROR: Startup of newrelic-plugin-agent Failed
.Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/helper/unix.py", line 91, in start
    self._daemonize()
  File "/usr/local/lib/python2.7/dist-packages/helper/unix.py", line 152, in _daemonize
    if os.getuid() != self.uid:
  File "/usr/local/lib/python2.7/dist-packages/helper/unix.py", line 139, in uid
    self._uid = pwd.getpwnam(self.config.daemon.user).pw_uid
KeyError: 'getpwnam(): name not found: newrelic'

Exception log: /var/log/newrelic-plugin-agent.errors

root@ip-10-11-13-114:/etc/newrelic# newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg -f
INFO       2015-03-12 08:24:32,123 32494  MainProcess     MainThread newrelic_plugin_agent.agent                   __init__                  L55    : Agent v1.3.0 initialized, Linux-3.13.0-44-generic-x86_64-with-glibc2.4 (Ubuntu 14.04 trusty) CPython v2.7.6
INFO       2015-03-12 08:24:32,124 32494  MainProcess     MainThread helper.controller                             run                       L251   : newrelic-plugin-agent v2.4.1 started
INFO       2015-03-12 08:24:32,124 32494  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: memcached
INFO       2015-03-12 08:24:32,125 32494  MainProcess     MainThread newrelic_plugin_agent.plugins.base            poll                      L277   : Polling Memcached
INFO       2015-03-12 08:24:32,126 32494  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L140   : Memcached poll successful, completed in 0.00 seconds
INFO       2015-03-12 08:24:32,126 32494  MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L220   : Sending 23 metrics to NewRelic
INFO       2015-03-12 08:24:32,377 32494  MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L133   : Stats processed in 0.25 seconds, next wake in 59 seconds
INFO       2015-03-12 08:25:32,124 32494  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: memcached
INFO       2015-03-12 08:25:32,124 32494  MainProcess     MainThread newrelic_plugin_agent.plugins.base            poll                      L277   : Polling Memcached
INFO       2015-03-12 08:25:32,125 32494  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L140   : Memcached poll successful, completed in 0.00 seconds
INFO       2015-03-12 08:25:32,125 32494  MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L220   : Sending 23 metrics to NewRelic
INFO       2015-03-12 08:25:32,367 32494  MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L133   : Stats processed in 0.24 seconds, next wake in 59 seconds
INFO       2015-03-12 08:26:32,124 32494  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: memcached
INFO       2015-03-12 08:26:32,125 32494  MainProcess     MainThread newrelic_plugin_agent.plugins.base            poll                      L277   : Polling Memcached
INFO       2015-03-12 08:26:32,125 32494  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L140   : Memcached poll successful, completed in 0.00 seconds
INFO       2015-03-12 08:26:32,126 32494  MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L220   : Sending 23 metrics to NewRelic
INFO       2015-03-12 08:26:32,371 32494  MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L133   : Stats processed in 0.25 seconds, next wake in 59 seconds

**Comment by esposj** [comment]
Hello, I am seeing the same (or similar) issue.  I can run in the foreground without a problem, but when using the init script, I get the error:

ERROR      2015-03-19 07:36:16,281 36217  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L276   : Enabled plugin redis not available

This happens when issuing the command from the command line too.
/usr/bin/python /usr/bin/newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg shows the above error
/usr/bin/python /usr/bin/newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg -f works without problem, parses both redis stanzas and I see stats in New Relic.

I don't see anything particularly interesting in the init script, but am left wondering if I'm missing a 'python thing' with regards to environments, etc?  

 Any help appreciated!

**Comment by jarvinia** [comment]
I got a similar issue. when I run this command "newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg", that script will stop automatically in a few minutes.

**Comment by imreFitos** [comment]
I ran into this problem and found that the newrelic user didn't have permission to read the installed newrelic-plugin-agent directory. Foreground worked because then it was running as root.

**Comment by MichaelOsowski** [comment]
Here is what needs to be changed if the newrelic user is used.  
Go to /var/log and execute sudo chown -R newrelic newrelic This allows access to the log file
Go to /var/run and execute sudo chown -R newrelic newrelic This allows access to newrelic-plugin-agent.pid

**Comment by alawson107** [comment]
In addition to the access changes I had to modify the PID file location on line six of the service script (/etc/rc/d/init.d/newrelic-plugin-agent for Centos 7).  

From:
# pidfile: /var/run/newrelic-plugin-agent.pid
To:
# pidfile: /var/run/newrelic/newrelic-plugin-agent.pid

Without the change it would timeout after running for a couple of minutes saying it could not find the PID file.

**Comment by holms** [comment]
Is this plugin dead or what? half of issues has no replies from maintainers..

**Comment by adimarco** [comment]
@holms - yeah, this ticket has been open for a year, it looks pretty dead.

I did manage to fix the problem the ticket describes and get the service running on CentOS 7 by changing the pidfile path in the service script like @alawson107 suggests, and making sure the newrelic user owned /var/log/newrelic and /var/run/newrelic
