### ISSUE TITLE
Postgres 9.3 Newrelic Plugin Error 

### ISSUE THREAD

**Issue by around01** [MeetMe/newrelic-plugin-agent#399]
L256   : Attempting to import newrelic_plugin_agent.plugins.postgresql.PostgreSQL
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/newrelic_plugin_agent-1.3.0-py2.6.egg/newrelic_plugin_agent/agent.py", line 252, in _get_plugin
    module_handle = importlib.import_module(package)
  File "/usr/lib/python2.6/site-packages/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.6/site-packages/newrelic_plugin_agent-1.3.0-py2.6.egg/newrelic_plugin_agent/plugins/postgresql.py", line 6, in <module>
    import psycopg2
ImportError: No module named psycopg2
ERROR      2015-03-13 14:02:39,034 16064  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L276   : Enabled plugin postgresql not available
WARNING    2015-03-13 14:02:39,035 16064  MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L217   : No metrics to send to NewRelic this interval
INFO       2015-03-13 14:02:39,035 16064  MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L133   : Stats processed in 0.00 seconds, next wake in 59 seconds

**Comment by Gnafu** [comment]
Hi, have you tried to install the additional requirements for PostgreSQL?
https://github.com/MeetMe/newrelic-plugin-agent#installing-additional-requirements
