### ISSUE TITLE
uwsgi error

### ISSUE THREAD

**Issue by jarvinia** [MeetMe/newrelic-plugin-agent#403]
I can't run command on background. It runs for a few minutes and then disappear. I didn't get any errors from log file. I try to run it with option "-f, it gets some errors as below:

Traceback (most recent call last):
  File "/usr/local/bin/newrelic-plugin-agent", line 9, in <module>
    load_entry_point('newrelic-plugin-agent==1.3.0', 'console_scripts', 'newrelic-plugin-agent')()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 337, in main
    helper.start(NewRelicPluginAgent)
  File "/usr/local/lib/python2.7/dist-packages/helper/__init__.py", line 174, in start
    obj.start()
  File "/usr/local/lib/python2.7/dist-packages/helper/controller.py", line 266, in start
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/helper/controller.py", line 257, in run
    signal.pause()
  File "/usr/local/lib/python2.7/dist-packages/helper/controller.py", line 428, in _wake
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 118, in process
    self.start_plugin_polling()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 280, in start_plugin_polling
    self.config.application.get(plugin))
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 108, in poll_plugin
    thread.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 308, in thread_process
    obj.poll()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/plugins/base.py", line 287, in poll
    data = self.fetch_data(connection)
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/plugins/uwsgi.py", line 99, in fetch_data
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 255 column 3 (char 4550)

**Comment by patrick-minted** [comment]
I'm also hitting this problem. At the least, there's a bug in the logging setup so that this error isn't being captured. I'm working on getting more detail to report here.
