### ISSUE TITLE
crash with mongo support enabled

### ISSUE THREAD

**Issue by tchwpkgorg** [MeetMe/newrelic-plugin-agent#417]
When I enable mongo support in the plugin, it crashes as below. With mongo commented out in the config, or with wrong mongo port specified in the config, the plugin does not crash.

 # /usr/local/bin/newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg -f
INFO       2015-05-29 04:03:36,116 456    MainProcess     MainThread newrelic_plugin_agent.agent                   __init__                  L55    : Agent v1.3.0 initialized, Linux-3.2.0-70-virtual-x86_64-with-glibc2.4 (Ubuntu 12.04 precise) CPython v2.7.3
INFO       2015-05-29 04:03:36,117 456    MainProcess     MainThread helper.controller                             run                       L251   : newrelic-plugin-agent v2.4.1 started
INFO       2015-05-29 04:03:36,117 456    MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: mongodb
Traceback (most recent call last):
  File "/usr/local/bin/newrelic-plugin-agent", line 9, in <module>
    load_entry_point('newrelic-plugin-agent==1.3.0', 'console_scripts', 'newrelic-plugin-agent')()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 337, in main
    helper.start(NewRelicPluginAgent)
  File "/usr/local/lib/python2.7/dist-packages/helper/__init__.py", line 174, in start
    obj.start()
  File "/usr/local/lib/python2.7/dist-packages/helper/controller.py", line 266, in start
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/helper/controller.py", line 253, in run
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 118, in process
    self.start_plugin_polling()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 280, in start_plugin_polling
    self.config.application.get(plugin))
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 108, in poll_plugin
    thread.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 308, in thread_process
    obj.poll()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/plugins/mongodb.py", line 257, in poll
    self.get_and_add_db_stats()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/plugins/mongodb.py", line 197, in get_and_add_db_stats
    self.get_and_add_db_list(databases)
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/plugins/mongodb.py", line 216, in get_and_add_db_list
    self.add_datapoints(database, db.command('dbStats'))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 445, in command
    uuid_subtype, compile_re, **kwargs)[0]
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 351, in _command
    msg, allowable_errors)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 151, in _check_command_response
    errmsg = details["errmsg"]
KeyError: 'errmsg'

**Comment by tchwpkgorg** [comment]
Looks like it was crashing when connecting to mongos 2.4.12. It works OK with mongos 2.4.14.
