### ISSUE TITLE
Fails on startup vs. Redis for Windows (ValueError: too many values to unpack)

### ISSUE THREAD

**Issue by obscurerichard** [MeetMe/newrelic-plugin-agent#418]
When run vs. Redis 2.8.x for Windows, the newrelic-plugin-agent fails and exits at startup with the following error messages:

```
[root@rediscentos7 system]# /usr/bin/newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg -f
INFO       2015-06-02 17:49:11,128 3764   MainProcess     MainThread newrelic_plugin_agent.agent                   __init__                  L55    : Agent v1.3.0 initialized, Linux-3.10.0-229.el7.x86_64-x86_64-with-glibc2.2.5 (CentOS Linux 7.1.1503 Core) CPython v2.7.5
INFO       2015-06-02 17:49:11,129 3764   MainProcess     MainThread helper.controller                             run                       L251   : newrelic-plugin-agent v2.4.1 started
INFO       2015-06-02 17:49:11,129 3764   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: redis
INFO       2015-06-02 17:49:11,131 3764   MainProcess     MainThread newrelic_plugin_agent.plugins.base            poll                      L277   : Polling Redis
INFO       2015-06-02 17:49:11,133 3764   MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L140   : Redis poll successful, completed in 0.00 seconds
INFO       2015-06-02 17:49:11,133 3764   MainProcess     MainThread newrelic_plugin_agent.plugins.base            poll                      L277   : Polling Redis
INFO       2015-06-02 17:49:11,136 3764   MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L140   : Redis poll successful, completed in 0.00 seconds
INFO       2015-06-02 17:49:11,137 3764   MainProcess     MainThread newrelic_plugin_agent.plugins.base            poll                      L277   : Polling Redis
Traceback (most recent call last):
  File "/usr/bin/newrelic-plugin-agent", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/newrelic_plugin_agent/agent.py", line 337, in main
    helper.start(NewRelicPluginAgent)
  File "/usr/lib/python2.7/site-packages/helper/__init__.py", line 174, in start
    obj.start()
  File "/usr/lib/python2.7/site-packages/helper/controller.py", line 266, in start
    self.run()
  File "/usr/lib/python2.7/site-packages/helper/controller.py", line 253, in run
    self.process()
  File "/usr/lib/python2.7/site-packages/newrelic_plugin_agent/agent.py", line 118, in process
    self.start_plugin_polling()
  File "/usr/lib/python2.7/site-packages/newrelic_plugin_agent/agent.py", line 280, in start_plugin_polling
    self.config.application.get(plugin))
  File "/usr/lib/python2.7/site-packages/newrelic_plugin_agent/agent.py", line 108, in poll_plugin
    thread.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/newrelic_plugin_agent/agent.py", line 308, in thread_process
    obj.poll()
  File "/usr/lib/python2.7/site-packages/newrelic_plugin_agent/plugins/base.py", line 287, in poll
    data = self.fetch_data(connection)
  File "/usr/lib/python2.7/site-packages/newrelic_plugin_agent/plugins/redis.py", line 148, in fetch_data
    key, value = line.strip().split(':')
ValueError: too many values to unpack
```

Here are the basic configurations of the Windows redis servers:

```
$ redis-cli  -h redis.example.com info
# Server
redis_version:2.8.19
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:9968db13395be4aa
redis_mode:standalone
os:Windows
arch_bits:64
multiplexing_api:winsock_IOCP
gcc_version:0.0.0
process_id:2192
run_id:bd82c38d1c367b1f91c44f77de05e430678732ba
tcp_port:6379
uptime_in_seconds:27982
uptime_in_days:0
hz:10
lru_clock:7219752
config_file:C:\redis\redis.windows.conf
...
$ redis-cli -h redis2.example.com info
# Server
redis_version:2.8.17
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:e1f61e287dff4649
redis_mode:standalone
os:Windows
arch_bits:64
multiplexing_api:winsock_IOCP
gcc_version:0.0.0
process_id:1400
run_id:8528d014fbce764028c12f787d0a932cfdd7cc48
tcp_port:6379
uptime_in_seconds:79716
uptime_in_days:0
hz:10
lru_clock:7219954
config_file:C:\redis-2.8.17/redis.windows.conf

$ cat //redis.example.com/c\$/redis/redis.windows.conf | grep -v '^#' | sort -u

activerehashing yes
aof-rewrite-incremental-fsync yes
appendfsync everysec
appendonly no
auto-aof-rewrite-min-size 64mb
auto-aof-rewrite-percentage 100
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit pubsub 32mb 8mb 60
client-output-buffer-limit slave 256mb 64mb 60
databases 16
dbfilename dump.rdb
dir ./
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
hz 10
list-max-ziplist-entries 512
list-max-ziplist-value 64
logfile c:\redis\redis.log
loglevel notice
lua-time-limit 5000
maxmemory 512mb
no-appendfsync-on-rewrite no
port 6379
rdbchecksum yes
rdbcompression yes
repl-disable-tcp-nodelay no
save 300 10
save 60 10000
save 900 1
set-max-intset-entries 512
slave-priority 100
slave-read-only yes
slave-serve-stale-data yes
slaveof 10.0.0.121 6379
slowlog-log-slower-than 10000
slowlog-max-len 128
stop-writes-on-bgsave-error yes
syslog-enabled no
tcp-keepalive 0
timeout 0
zset-max-ziplist-entries 128
zset-max-ziplist-value 64

```
The fix for this is pretty simple, expect a pull request soon.

**Comment by obscurerichard** [comment]
Pretty please consider merging pull request #419 and closing this issue with a successful resolution.

**Comment by obscurerichard** [comment]
I expect that the parsing is choking on:

```
config_file:C:\redis\redis.windows.conf
```

since there is more than 1 `:` character in the line.
