### ISSUE TITLE
Newrelic-plugin-agent Fails on start with error

### ISSUE THREAD

**Issue by marcusl33beach** [MeetMe/newrelic-plugin-agent#420]
I am running centos 6.6 and the Newrelic-plugin-agent is failing on start with error:
````
# /usr/bin/newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg -f
Traceback (most recent call last):
  File "/usr/bin/newrelic-plugin-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.0.0
```

Any idia?

**Comment by marcusl33beach** [comment]
After a bit of troubleshooting I believe this is an issue due to the fact that centos 6.6 system python is 0.2.6 and this plugin looks to only working well with 0.2.7. There are a few other posts about updating to version 0.2.7, but I we are not going to be updating anytime soon. So I need a workaround for 0.2.6.

**Comment by marcusl33beach** [comment]
So to make this work on CentOS 6 I did the following:
```
yum install python-pip.noarch'
yum install 'gcc'
yum install 'python-devel.x86_64'
yum install 'libffi-devel.x86_64'
yum install  'openssl-devel'
```
Then the following commands:
```
pip install -U setuptools
pip install -U requests
pip install requests[security]
pip install -U ndg-httpsclient
pip install newrelic-plugin-agent
```
