### ISSUE TITLE
Getting error pkg_resources.DistributionNotFound: requests>=2.0.0

### ISSUE THREAD

**Issue by nikhilpavithran** [MeetMe/newrelic-plugin-agent#448]
Hi,
I tried to configure this plugin of IBM IHS web server. Currently getting the below error while running this agent..

~~~~~~~~~~~~~~
[root@cksitapp01 newrelic-plugin-agent]# newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg
Traceback (most recent call last):
  File "/usr/bin/newrelic-plugin-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.0.0


~~~~~~~~~~~~~~
[root@cksitapp01 newrelic]# pip list | egrep "(newrelic|requests)"
newrelic-plugin-agent (1.3.0)
requests (2.7.0)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Please let me know how to solve this issue.

Please

**Comment by chromerobv** [comment]
same issue 
newrelic-plugin-agent (1.3.0)
requests (2.8.1)

**Comment by chromerobv** [comment]
https://github.com/MeetMe/newrelic-plugin-agent/issues/420
