### ISSUE TITLE
Getting error - TypeError: string indices must be integers, not str when installing newrelic plugin

### ISSUE THREAD

**Issue by p2p-mdurbha** [MeetMe/newrelic-plugin-agent#495]
I downloaded the 1.3 version of your plugin and went thru all the steps.  I get the error below when I try to start the plugin.  Please help!
My Python version is 2.7

root@p2n-sfo-db-demo01:/var/lib/postgresql/utils/newrelic_plugin_agent-1.3.0/etc/newrelic# newrelic-plugin-agent -c ./newrelic-plugin-agent.cfg
Traceback (most recent call last):
  File "/usr/local/bin/newrelic-plugin-agent", line 9, in <module>
    load_entry_point('newrelic-plugin-agent==1.3.0', 'console_scripts', 'newrelic-plugin-agent')()
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 337, in main
    helper.start(NewRelicPluginAgent)
  File "/usr/local/lib/python2.7/dist-packages/helper/**init**.py", line 171, in start
    obj = ctrl(args, platform.operating_system())
  File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 41, in **init**
    super(NewRelicPluginAgent, self).**init**(args, operating_system)
  File "/usr/local/lib/python2.7/dist-packages/helper/controller.py", line 89, in **init**
    self.config = config.Config(args.config)
  File "/usr/local/lib/python2.7/dist-packages/helper/config.py", line 67, in **init**
    self._assign_values(self.application, self._values.get('Application'))
  File "/usr/local/lib/python2.7/dist-packages/helper/config.py", line 78, in _assign_values
    setattr(obj, key, values[key])
TypeError: string indices must be integers, not str

**Comment by p2p-mdurbha** [comment]
Any help on this? Thanks
