### ISSUE TITLE
New Relic Apache plugin not working

### ISSUE THREAD

**Issue by dnpmoris** [MeetMe/newrelic-plugin-agent#522]
------------------------------------------------------------------------ [START]
/bin/newrelic-plugin-agent Exception [2017-05-30T12:09:02.790270]
------------------------------------------------------------------------- [INFO]
Interpreter: /usr/bin/python
CLI arguments: /bin/newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg
Exception: 'getpwnam(): name not found: newrelic'
Traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/helper/unix.py", line 91, in start
    self._daemonize()
  File "/usr/lib/python2.7/site-packages/helper/unix.py", line 152, in _daemonize
    if os.getuid() != self.uid:
  File "/usr/lib/python2.7/site-packages/helper/unix.py", line 139, in uid
    self._uid = pwd.getpwnam(self.config.daemon.user).pw_uid
KeyError: 'getpwnam(): name not found: newrelic'
-------------------------------------------------------------------------- [END]
(END)

**Comment by dnpmoris** [comment]
Please help me how to fix this error

**Comment by benburleson** [comment]
Does your server have a `newrelic` user?

If not, try running `useradd newrelic` and see if that fixes it. Or in your config file, choose a different user.
