### ISSUE TITLE
Httpd Plugin not working

### ISSUE THREAD

**Issue by arvind-sawant** [MeetMe/newrelic-plugin-agent#523]
Hi I have install Httpd Plugin and able to start newrelic-plugin-agent service too but in newrelic-plugin-agent.log i am getting below error 

INFO       2017-06-08 07:29:44,460 6927   MainProcess     MainThread newrelic_plugin_agent.agent                   __init__                  L55    : Agent v1.3.0 initialized, Linux-4.9.27-14.31.amzn1.x86_64-x86_64-with-glibc2.3.4 CPython v3.5.1
INFO       2017-06-08 07:29:44,461 6927   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: apache_httpd
ERROR      2017-06-08 07:29:44,463 6927   MainProcess     MainThread newrelic_plugin_agent.agent                   _get_plugin               L256   : Attempting to import newrelic_plugin_agent.plugins.apache_httpd.ApacheHTTPD
Traceback (most recent call last):
  File "/usr/lib/python3.5/dist-packages/newrelic_plugin_agent/agent.py", line 252, in _get_plugin
    module_handle = importlib.import_module(package)
  File "/usr/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3.5/dist-packages/newrelic_plugin_agent/plugins/apache_httpd.py", line 8, in <module>
    from newrelic_plugin_agent.plugins import base
  File "/usr/lib/python3.5/dist-packages/newrelic_plugin_agent/plugins/base.py", line 12, in <module>
    import urlparse
ImportError: No module named 'urlparse'

Thanks
Arvind

**Comment by arvind-sawant** [comment]
There is two version in system so i remove python3.5 version and it work now.
