### ISSUE TITLE
ImportError: No module named 'Queue'

### ISSUE THREAD

**Issue by miketdollar** [MeetMe/newrelic-plugin-agent#557]
I'm wondering what I'm missing. I'm using ubuntu 16 LTS and setup a newrelic user account on the system.  I'm using python3 and have installed python3-pip, python3-setuptools, pip has been upgraded and I was able to install the newrelic-plugin-agent.  I've also installed the npi under the newrelic user account.  When I try to run the newrelic-plugin-agent however I get the below error.  

~# newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg
Traceback (most recent call last):
  File "/usr/local/bin/newrelic-plugin-agent", line 9, in <module>
    load_entry_point('newrelic-plugin-agent==1.3.0', 'console_scripts', 'newrelic-plugin-agent')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/newrelic_plugin_agent/agent.py", line 13, in <module>
    import Queue as queue
ImportError: No module named 'Queue'

**Comment by srabouin** [comment]
Use python 2 ... worked for me!
