### ISSUE TITLE
Newrelic PostgreSQL Plugin agent failing

### ISSUE THREAD

**Issue by akoregaonkar** [MeetMe/newrelic-plugin-agent#563]
After starting Newrelic Postgres plugin it got failed unexpectedly. The error is showing:

INFO 2019-12-10 05:33:34,791 39954 MainProcess MainThread newrelic_plugin_agent.agent start_plugin_polling L263 : Enabling plugin: postgresql
INFO 2019-12-10 05:33:36,119 39954 MainProcess MainThread newrelic_plugin_agent.plugins.base finish L140 : PostgreSQL poll successful, completed in 1.33 seconds
INFO 2019-12-10 05:33:36,119 39954 MainProcess MainThread newrelic_plugin_agent.agent start_plugin_polling L263 : Enabling plugin: pgbouncer
INFO 2019-12-10 05:33:36,123 39954 MainProcess MainThread newrelic_plugin_agent.plugins.base finish L140 : PgBouncer poll successful, completed in 0.00 seconds
INFO 2019-12-10 05:33:36,123 39954 MainProcess MainThread newrelic_plugin_agent.agent send_components L220 : Sending 121 metrics to NewRelic
Traceback (most recent call last):
File "/usr/local/bin/newrelic-plugin-agent", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 337, in main
helper.start(NewRelicPluginAgent)
File "/usr/local/lib/python2.7/dist-packages/helper/__init__.py", line 174, in start
obj.start()
File "/usr/local/lib/python2.7/dist-packages/helper/controller.py", line 266, in start
self.run()
File "/usr/local/lib/python2.7/dist-packages/helper/controller.py", line 257, in run
signal.pause()
File "/usr/local/lib/python2.7/dist-packages/helper/controller.py", line 428, in _wake
self.process()
File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 125, in process
self.send_data_to_newrelic()
File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 209, in send_data_to_newrelic
self.send_components(components, metrics)
File "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py", line 227, in send_components
data=json.dumps(body, ensure_ascii=False),
File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
sort_keys=sort_keys, **kw).encode(obj)
File "/usr/lib/python2.7/json/encoder.py", line 208, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/lib/python2.7/json/encoder.py", line 271, in iterencode
return _iterencode(o, 0)
File "/usr/lib/python2.7/json/encoder.py", line 185, in default
raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Decimal('157068390') is not JSON serializable

**Comment by dattatraya-nirmal** [comment]
Need to add support for `Decimal` objects in agent.py file. 
Applying below patch will fix this error -

```
--- /usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py  2020-07-23 07:29:22.000532835 -0600
+++ /usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py.updated       2020-07-23 07:30:46.924265186 -0600
@@ -4,7 +4,7 @@
 """
 import helper
 import importlib
-import json
+import json, decimal
 import logging
 import os
 import requests
@@ -19,6 +19,13 @@

 LOGGER = logging.getLogger(__name__)

+class _CustomJSONEncoder(json.JSONEncoder):
+
+    def default(self, o):
+        if isinstance(o, decimal.Decimal):
+            return float(o)
+        # Provide a fallback to the default encoder if we haven't implemented special support for the object's class
+        return super(_CustomJSONEncoder, self).default(o)

 class NewRelicPluginAgent(helper.Controller):
     """The NewRelicPluginAgent class implements a agent that polls plugins
@@ -224,7 +231,7 @@
             response = requests.post(self.endpoint,
                                      headers=self.http_headers,
                                      proxies=self.proxies,
-                                     data=json.dumps(body, ensure_ascii=False),
+                                     data=json.dumps(body, cls=_CustomJSONEncoder, ensure_ascii=False),
                                      timeout=self.config.get('newrelic_api_timeout', 10),
                                      verify=self.config.get('verify_ssl_cert',
                                                             True))



```

**Comment by akoregaonkar** [comment]
@dattatraya-nirmal Thank you. It helped and resolved issue.
